export { ENGINE_VERSION } from './version'
export * from './types'
export { monthlyTotals, trailingFullMonths, monthToDateSpendByCategory, periodBounds, signedFlows } from './aggregates'
export { detectAnomalies } from './anomaly'
export { computeHealthScore } from './score'
export { detectRecurrence } from './recurrence'
export { computeForecast } from './forecast'
export { simulatePurchase, simulateSaveMore, simulateIncomeChange } from './simulation'
export { classifyIntent, resolvePeriod, monthLabelEs } from './intent'
export { buildFactsPayload, recentTransactions } from './facts'
export { normalizeCategorySlug, categoryLabel, detectCategoryInText, CATEGORY_LABELS_ES } from './categories'
export { isoDate, startOfMonth, endOfMonth } from './period'
export { round2, clamp, median, mean } from './stats'
export { APP_TIME_ZONE, toLocalDay, localDayOf, localToday, isValidDate } from './timezone'
