export { ENGINE_VERSION } from './version'
export * from './types'
export { monthlyTotals, trailingFullMonths, monthToDateSpendByCategory, periodBounds, signedFlows } from './aggregates'
export { detectAnomalies } from './anomaly'
export { computeHealthScore } from './score'
export { detectRecurrence } from './recurrence'
export { computeForecast } from './forecast'
export { simulatePurchase, simulateSaveMore, simulateIncomeChange } from './simulation'
export { classifyIntent } from './intent'
export { buildFactsPayload } from './facts'
export { isoDate, startOfMonth, endOfMonth } from './period'
export { round2, clamp, median, mean } from './stats'
