-- Migration: Proactive Events Table
-- Description: Stores proactive notifications, triggers, and intelligence events generated by Nina OS.

CREATE TABLE IF NOT EXISTS public.proactive_events (
    id UUID DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    type VARCHAR(50) NOT NULL, -- e.g., 'insight', 'warning', 'goal', 'anomaly', 'encouragement'
    severity VARCHAR(20) NOT NULL, -- 'low', 'medium', 'high', 'critical'
    payload JSONB NOT NULL DEFAULT '{}'::jsonb, -- contains triggers, messages, riskProfile
    read_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for fast queries by user and chronological ordering
CREATE INDEX idx_proactive_events_user_id ON public.proactive_events(user_id);
CREATE INDEX idx_proactive_events_created_at ON public.proactive_events(created_at DESC);
CREATE INDEX idx_proactive_events_unread ON public.proactive_events(user_id) WHERE read_at IS NULL;

-- Setup RLS
ALTER TABLE public.proactive_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own proactive events"
    ON public.proactive_events FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can update read_at for their own events"
    ON public.proactive_events FOR UPDATE
    USING (auth.uid() = user_id);
